<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>promise学习</title>
</head>
<body>

<script>
	/*
		Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。
		Promise对象有以下两个特点。

		（1）对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是Promise这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。

		（2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从pending变为fulfilled和从pending变为rejected。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为 resolved（已定型）。如果改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。

		const getJSON = function(url) {
		  	const promise = new Promise(function(resolve, reject){
		    const handler = function() {
		      if (this.readyState !== 4) {
		        return;
		      }
		      if (this.status === 200) {
		        resolve(this.response);
		      } else {
		        reject(new Error(this.statusText));
		      }
		    };
		    const client = new XMLHttpRequest();
		    client.open("GET", url);
		    client.onreadystatechange = handler;
		    client.responseType = "json";
		    client.setRequestHeader("Accept", "application/json");
		    client.send();

		  });

		  return promise;
		};

		getJSON("/posts.json").then(function(json) {
		  console.log('Contents: ' + json);
		}, function(error) {
		  console.error('出错了', error);
		});

		一个异步操作的结果是返回另一个异步操作。
		const p1 = new Promise(function (resolve, reject) {
		  setTimeout(() => reject(new Error('fail')), 3000)
		})

		const p2 = new Promise(function (resolve, reject) {
		  setTimeout(() => resolve(p1), 1000)
		})

		p2
		  .then(result => console.log(result))
		  .catch(error => console.log(error))
		
		Promise.prototype.then()
		then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。
		getJSON("/posts.json").then(function(json) {
		  return json.post;
		}).then(function(post) {
		  // ...
		});
		上面的代码使用then方法，依次指定了两个回调函数。第一个回调函数完成以后，会将返回结果作为参数，传入第二个回调函数。

		Promise.prototype.catch()
		Promise.prototype.catch方法是.then(null, rejection)的别名，用于指定发生错误时的回调函数。

		如果 Promise 状态已经变成resolved，再抛出错误是无效的。
		const promise = new Promise(function(resolve, reject) {
		  resolve('ok');
		  throw new Error('test');
		});
		promise
		  .then(function(value) { console.log(value) })
		  .catch(function(error) { console.log(error) });
		// ok
		上面代码中，Promise 在resolve语句后面，再抛出错误，不会被捕获，等于没有抛出。因为 Promise 的状态一旦改变，就永久保持该状态，不会再变了。

		//Promise.prototype.finally()
		finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。
		finally方法的回调函数不接受任何参数，这意味着没有办法知道，前面的 Promise 状态到底是fulfilled还是rejected。这表明，finally方法里面的操作，应该是与状态无关的，不依赖于 Promise 的执行结果。

		//Promise.all()
		Promise.all方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。

		const p = Promise.all([p1, p2, p3]);haoai

		p的状态由p1、p2、p3决定，分成两种情况。

		（1）只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。

		（2）只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数。

		//Promise.race()
		Promise.race方法同样是将多个 Promise 实例，包装成一个新的 Promise 实例。
		const p = Promise.race([p1, p2, p3]);
		上面代码中，只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给p的回调函数。

		//Promise.resolve()
		有时需要将现有对象转为 Promise 对象，Promise.resolve方法就起到这个作用。
		Promise.resolve('foo')
		// 等价于
		new Promise(resolve => resolve('foo'))

		Promise.resolve方法的参数分成四种情况。
		（1）参数是一个 Promise 实例
		（2）参数是一个thenable对象
		（3）参数不是具有then方法的对象，或根本就不是对象
		（4）不带有任何参数
	*/
</script>
</body>
</html>